In [1]:
import numpy as np

In [2]:
test_array = np.array(range(10))
print(test_array)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
print(test_array[::2])
print(test_array[1::2])

[0 2 4 6 8]
[1 3 5 7 9]


In [1]:
import os
print(sorted(os.listdir('./')))

['.git', '.github', '.gitignore', 'AttentionGraphs.ipynb', 'JetClass_example_100k_jet_eta.npy', 'JetClass_example_100k_jet_phi.npy', 'LICENSE', 'MoE_AttentionGraphs.ipynb', 'MoeParticleTransformer.py', 'MoeParticleTransformer.py:Zone.Identifier', 'MoeRouterHooks.ipynb', 'MoeRouterHooks_expert_ablation.ipynb', 'MoeRouterHooks_job.ipynb', 'MoeStackedBar_job.py', 'MoeStackedBar_job_ll.py', 'MoeStackedBar_job_seed_1.py', 'MoeStackedBar_pid_job.py', 'MoeStackedBar_plot_Higgs_4Q_100k.png', 'MoeStackedBar_plot_Higgs_BB_100k.png', 'MoeStackedBar_plot_Higgs_CC_100k.png', 'MoeStackedBar_plot_Higgs_GG_100k.png', 'MoeStackedBar_plot_Higgs_QQL_100k.png', 'MoeStackedBar_plot_QCD_100k.png', 'MoeStackedBar_plot_Top_BL_100k.png', 'MoeStackedBar_plot_Top_BQQ_100k.png', 'MoeStackedBar_plot_W_QQ_100k.png', 'MoeStackedBar_plot_Z_QQ_100k.png', 'MoeStackedBar_plotting.py', 'MoeStackedBar_plotting_ll.py', 'MoeStackedBar_plotting_seed_1.py', 'Moe_PCA_study.ipynb', 'ParT_AttentionGraphs.ipynb', 'README.md', 'ch

In [2]:
print(-1%8)

7
