In [1]:
import numpy as np

In [2]:
test_array = np.array(range(10))
print(test_array)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
print(test_array[::2])
print(test_array[1::2])

[0 2 4 6 8]
[1 3 5 7 9]


In [ ]:
import os
print(sorted(os.listdir('./')))